### ISSUE TITLE
windows报错

### ISSUE THREAD

**Issue by zhangpenglink** [cupools/lia#5]
node v8.9.1
```
C:\Users\zhangpeng\AppData\Roaming\npm\node_modules\lia\node_modules\images\scripts\util\binding.js:15
      throw new Error(errors.missingBinary());
      ^

Error: Missing binding C:\Users\zhangpeng\AppData\Roaming\npm\node_modules\lia\node_modules\images\vendor\win32-x64-57\binding.node
imagescould not find a binding for your current environment: Windows 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x
  - Windows 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild images --force` to build the binding for your current environment.
    at module.exports (C:\Users\zhangpeng\AppData\Roaming\npm\node_modules\lia\node_modules\images\scripts\util\binding.js:15:13)
    at Object.<anonymous> (C:\Users\zhangpeng\AppData\Roaming\npm\node_modules\lia\node_modules\images\index.js:32:51)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\zhangpeng\AppData\Roaming\npm\node_modules\lia\lib\utils\image.js:11:15)
```

**Comment by cupools** [comment]
看日志猜测是在旧版本 Node 安装了依赖包，而后更新了 Node 导致的不兼容。可以试试删除 `node_modules` 然后重新安装 `npm i`

**Comment by zhangpenglink** [comment]
果然~~谢谢
